package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"time"

	"github.com/ebbele/rygo-pulse/backend/graph/model"
	"github.com/google/uuid"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	todo := &model.Todo{
		ID:   uuid.New().String(),
		Text: input.Text,
	}

	r.TodoService.Publish(input.UserID, todo)

	// just some debug print to see whats published for whom
	fmt.Printf("Published: %s => %s for %s\n", todo.ID, todo.Text, input.UserID)

	return todo, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	// Feel free to work with it
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// TodoCreated is the resolver for the todoCreated field.
func (r *subscriptionResolver) TodoCreated(ctx context.Context, userID string) (<-chan *model.Todo, error) {
	ch := r.TodoService.Subscribe(userID)

	// debug info in subscription
	fmt.Printf("Todo subscriber created for: %s\n", userID)

	go func() {
		<-ctx.Done()
		r.TodoService.Unsubscribe(userID)
	}()

	return ch, nil
}

// CurrentTime is the resolver for the currentTime field.
func (r *subscriptionResolver) CurrentTime(ctx context.Context) (<-chan string, error) {
	ch := make(chan string)

	// Optional: define interval, this is just used to simulate subscriptions
	interval := 1234 * time.Millisecond

	go func() {
		defer close(ch) // ensure the channel is closed when goroutine exits

		ticker := time.NewTicker(interval)
		defer ticker.Stop() // stop the ticker to avoid leaks

		for {
			select {
			case <-ctx.Done():
				// This triggers if the client unsubscribes or disconnects
				fmt.Println("Time subscription canceled, cleaning up.")
				return
			case t := <-ticker.C:
				// Send current time to the channel
				select {
				case ch <- t.String():
					// successfully sent
				case <-ctx.Done():
					// client disconnected before we could send
					fmt.Println("Time subscription canceled during send.")
					return
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
